export const SECTIONS = [
  {
    id: "intro",
    type: "welcome",
    title: "Let's sketch out your story.",
    subtitle:
      "This isn't a CV or a polished pitch - it's raw material for your story. Answer in your real voice, without trying to sound \"official.\"",
    cta: "Let's go",
  },
  {
    id: "project",
    label: "THE PROJECT",
    questions: [
      {
        id: "what_you_do",
        label: "In your own words, how do you describe what you do when you're talking to others in your industry? What about to your audience?",
        hint: "(Don't polish it. A messy brain dump is perfect.)",
        type: "textarea",
        required: true,
      },
      {
        id: "why_now",
        label: "What's not working about the current version of your brand. What's making you want to evolve it?",
        hint: "",
        type: "textarea",
        required: true,
      },
      {
        id: "platforms",
        label: "Where do you mostly show up and do business right now? List the main places: platforms, websites, communities, collaborations, and any IRL spaces/events.",
        hint: "",
        type: "textarea",
        required: true,
      },
    ],
  },
  {
    id: "audience",
    label: "YOUR AUDIENCE",
    questions: [
      {
        id: "primary_audience",
        label: "Who's your main audience right now? Who follows you closely or actually buys from you?",
        hint: "Describe them like real people: what are they hoping to feel, fix, escape, learn, or become when they come to you and your content?",
        type: "textarea",
        required: true,
      },
      {
        id: "why_they_choose_you",
        label: "When someone decides to hire you, what's usually happening? What do they say they're paying for when they choose you?",
        hint: "",
        type: "textarea",
        required: true,
      },
      {
        id: "biggest_objection",
        label: "What's the biggest hesitation you hear before someone commits?",
        hint: "(Price, uncertainty, time, fear of judgment, not clear on what they get, etc.)",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "positioning",
    label: "COMPETITION & POSITIONING",
    questions: [
      {
        id: "competitors",
        label: "Who else does what you do? List 2 to 5 creators or brands in your space (names, handles, links). Don't overthink it.",
        hint: "",
        type: "textarea",
        required: false,
      },
      {
        id: "what_makes_you_different",
        label: "What makes you the right choice over them?",
        hint: "One clear sentence. Not future-you, who you actually are right now.",
        type: "textarea",
        required: true,
      },
      {
        id: "proof_points",
        label: "Back it up.",
        hint: "Give 2 to 3 specifics: a skill you own, a track record, a niche audience you already have, something you do that others don't or won't.",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "brand",
    label: "YOUR BRAND CHARACTER",
    questions: [
      {
        id: "whats_off",
        label: "What feels confusing or \"off\" about your brand right now? Where do you notice inconsistency?",
        hint: "(Ex: Visuals, voice, content, offers, audience, opportunities)",
        type: "textarea",
        required: true,
      },
      {
        id: "brand_words",
        label: "If someone had to describe your brand in just 4-6 words, what would you want those words to be?",
        hint: "",
        type: "textarea",
        required: true,
      },
      {
        id: "feels_like",
        label: "What are 3 references you want this to feel like?",
        hint: "(Ex: brands, creators, films, photographers, fashion, hotels - anything)\n\nFor each one, tell me what you're borrowing (mood, pacing, color, tone, confidence, elegance, intimacy, edge, etc.).",
        type: "textarea",
        required: true,
      },
      {
        id: "avoid",
        label: "What are 3 things you absolutely don't want to be associated with anymore?",
        hint: "(Industry clichés, aesthetics, language, content, anything that makes you cringe.)",
        type: "textarea",
        required: true,
      },
      {
        id: "core_identity",
        label: "What's the core of you that can't change no matter how the brand evolves?",
        hint: "(Values, tone, the experience you create, what you stand for)",
        type: "textarea",
        required: false,
      },
      {
        id: "platform_restrictions",
        label: "Are there any rules we have to build around? Anything you can't say or show publicly?",
        hint: "(Platform restrictions, privacy, legal boundaries, or personal limits)",
        type: "textarea",
        required: false,
      },
      {
        id: "existing_assets",
        label: "What should I look at before I start?",
        hint: "Share any existing assets: old bios, brand decks, photography, social media, etc.",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "deliverables",
    label: "WHAT WE'RE BUILDING & WHERE WE'RE GOING",
    questions: [
      {
        id: "deliverables",
        label: "What specific deliverables are most important to you at the end of this project?",
        hint: "",
        type: "textarea",
        required: true,
      },
      {
        id: "if_this_works",
        label: "If this works, what does it unlock for you over the next 12 months (income, audience, opportunities, lifestyle, privacy, etc.)?",
        hint: "",
        type: "textarea",
        required: true,
      },
      {
        id: "anything_else",
        label: "Anything else I should know?",
        hint: "(Any weird context, sensitivities, \"sacred cows,\" things you've already tried, hard constraints, or instincts you want me to respect (or push back on)?)",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "submit",
    type: "submit",
    title: "That's everything.",
    subtitle: "I'll review this and we'll talk. Expect me to push back on a few things - that's the job.",
  },
];
